config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about' => 'pages#about'
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
       @articles = Article.all
    end

    def new
       @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was successfully created!"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
       @article = Article.find(params[:id])
    end

    def edit
       @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Article was successfully updated!"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def destroy
       @article = Article.find(params[:id])
       @article.destroy
       flash[:notice] = "Article was successfully deleted"
       redirect_to articles_path
    end

    private
    def article_params
       params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

    end

    def about

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h3>The following erros prevented the articles from being created:</h3>
<ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @article do |f| %>
<p>
    <%= f.label :title %></br>
    <%= f.text_field :title %>
</p>
<p>
    <%= f.label :description %></br>
    <%= f.text_area :description %>
</p>

<p>
    <%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<p><%= link_to "Back to articles listing", articles_path %></p>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<p><%= link_to "New Article", new_article_path %></p>

<table>
    <tr>
        <th>Title</th>
        <th>Description</th>
    </tr>
    <% @articles.each do |a| %>
    <tr>
        <td><%= a.title %></td>
        <td><%= a.description %></td>
        <td><%= link_to "Edit", edit_article_path(a) %> | </td>
        <td><%= link_to "Show", article_path(a) %> | </td>
        <td><%= link_to "Delete", article_path(a), method: :delete, data: {confirm: "Are you sure?"} %></td>
    </tr>
    <% end %>
</table>

</table>

app/views/articles/new.html.erb
<h1>Create Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.description %></p>

<p><%= link_to "Edit", edit_article_path(@article) %> | <%= link_to "Back", articles_path %></p>
<%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"} %></p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<ul>

<li><%= msg %></li>

</ul>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/messages' %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<html>
    <head>
        <title>About</title>
    </head>
    <body>

        <h1>About</h1>

        <%= link_to 'Home', root_path %>

    </body>

</html>

app/views/pages/home.html.erb
<html>
    <head>
        <title>Home</title>
    </head>
    <body>

        <h1>Home</h1>
<%= link_to "Alpha Blog", articles_path %>
        <%= link_to 'About', about_path %>

    </body>

</html>